import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout/Layout';
import { IBlogCard } from '../components/Blogs/blog-card';
import { BlogLists } from '../components/Blogs/blogs-lists';
import VideoCardLists from '../components/Video/video-card-lists';
import { HeroSection } from '../components/HeroSection';
import VideoSection from '../components/VideoSection';
import Slogans from '../components/Slogs';

export const blogsLists: IBlogCard[] = [
  {
    slug: 'asd',
    src: 'https://c.ndtvimg.com/2021-12/nie2c78g_president-ram-nath-kovind-ima-passing-out-parade-twitter_625x300_11_December_21.jpg?im=Resize=(1230,900)',
    title: 'asdasd',
  },
  {
    slug: 'asd',
    src: 'https://c.ndtvimg.com/2021-12/nie2c78g_president-ram-nath-kovind-ima-passing-out-parade-twitter_625x300_11_December_21.jpg?im=Resize=(1230,900)',
    title: 'asdasd',
  },
  {
    slug: 'asd',
    src: 'https://c.ndtvimg.com/2021-12/nie2c78g_president-ram-nath-kovind-ima-passing-out-parade-twitter_625x300_11_December_21.jpg?im=Resize=(1230,900)',
    title: 'asdasd',
  },
];

const Home: NextPage = () => {
  return (
    <Layout>
      <div>
        <Head>
          <title>Hamro Nepal </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="relative">
          <section>
            <Slogans />
          </section>
          <section className="">
            <HeroSection />
          </section>
        </div>
        <section className="mt-[220px]">
          <VideoSection />
        </section>
        <section className="mt-[50px]">
          <BlogLists blogsLists={blogsLists} />
        </section>
        <section className="mt-[120px]">
          <VideoCardLists videoLists={blogsLists} />
        </section>
      </div>
    </Layout>
  );
};

export default Home;
